name: Continuous Integration

on:
  push:
    branches: ['*']
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.0
            os: ubuntu-20.04
          - ruby: ruby-2.7
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: test -e Gemfile.lock
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bin/rspec
